### ISSUE TITLE
Any reason image_url is not supported?

### ISSUE THREAD

**Issue by jpshook** [peterruggero/postmaster-csharp#24]
Is there a technical reason that image_url is not currently supported?

**Comment by CountZachula** [comment]
@jpshook,

Are you referring to the LabelUrl in the Shipment entity or ImageUrl in the FitResponseBody entity?

Thanks!

FitResponseBody.cs: https://github.com/postmaster/postmaster-csharp/blob/master/source/postmaster.io/Api/V1/Entities/Box/FitResponseBody.cs

Package: https://github.com/postmaster/postmaster-csharp/blob/master/source/postmaster.io/Api/V1/Entities/Shipment/Package.cs

**Comment by jpshook** [comment]
Sorry, I posted my question before really digging into the code.  

When I use the default request values from the docs, my response object does not contain a image_url value for each box and there is not even a property (that I can tell) for the image_url for each step of the packing for the items.  Also, in the request, I am not seeing any property for the "generating_img" parameter.

I just modified the fit method to reveal the raw json request and response content and the image_url do have values in the json string.

**Comment by jpshook** [comment]
Here is the code I am using for my local demo MVC controller action.

```
public ActionResult PostmasterIoDemo() {

  Test model = new Test();

  // set Postmaster API key (only required once per session if set at application startup)
  Postmaster.io.Postmaster.Init("tt_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

  //NOTE: boxes are optional - can use Create Box api to build internal list of boxes.

  // instantiate using object initializer syntax
  FitRequest fitRequest = new FitRequest {
    Items = new List<Item> {
    new Item {
        Width = 2.2,
        Length = 3,
        Height = 1,
        Count = 2,
        Sku = "123ABC",
        Name = "Some product name"
    }
},
    Packages = new List<Box> {
    new Box {
        Width = 6,
        Length = 6,
        Height = 6
    },
    new Box {
        Width = 12,
        Length = 12,
        Height = 12
    }
}
  };


  string jsonRequest = "";
  string jsonResponse = "";

  // fit items in box
  FitResponse response = fitRequest.Fit(out jsonRequest, out jsonResponse);

  model.DebugMsgs.Add("All fit: " + response.AllFit.ToString());

  int i = 0;

  model.DebugMsgs.Add("JSON request: " + jsonRequest);
  model.DebugMsgs.Add("JSON response: " + jsonResponse);


  foreach (var pkg in response.Boxes) {
    i++;
    model.DebugMsgs.Add("*******************************************************************");
    model.DebugMsgs.Add("Package #" + i.ToString());
    model.DebugMsgs.Add("Dims: " + pkg.Box.Length.ToString() + "\" x " + pkg.Box.Width.ToString() + "\" x " + pkg.Box.Height.ToString() + "\" - " + pkg.Box.Weight.ToString() + "lbs. ");
    model.DebugMsgs.Add("Packed box image: " + pkg.ImageUrl);

    model.DebugMsgs.Add("Items in Package:");
    int j = 0;
    foreach (var item in pkg.Items) {
      j++;
      model.DebugMsgs.Add("Dims: " + item.Length.ToString() + "\" x " + item.Width.ToString() + "\" x " + item.Height.ToString() + "\" - " + item.Weight.ToString() + "lbs. ");
      model.DebugMsgs.Add("name: " + item.Name + " - sku: " + item.Sku);
      //The response demo shows a image_url for each box as a packing step - but this is not yet exposed in the .net wrapper.
    }
  }

  if (response.Leftovers.Count > 0) { 

    model.DebugMsgs.Add("Leftovers: " + response.Leftovers.ToString());

  }

  model.DebugMsgs.Add("boxes: " + response.Boxes.ToString());

  return View(ViewBasePath + @"Test\Test.cshtml", model);

}
```

**Comment by CountZachula** [comment]
@jpshook,

My apologies. There was a server-side API change that the FitResponse entity doesn't correctly reflect. We are currently looking into the issue and will keep you updated. Some of the other client libraries may also be affected.

As a workaround, if you download the source, you can achieve what you are wanting by following these steps:

• Remove the ImageUrl property from FitResponseBody.cs
• Add the ImageUrl property to FitResponse.cs
• Add the ImageUrl property to Item.cs

You can then access the final ImageUrl from the FitResponse entity OR each item's ImageUrl from the Item entities.

We will keep this issue open and updated.

Thanks!

**Comment by jpshook** [comment]
I will try that, but according to the docs, the ImageUrl for the box needs to be at the same level as FitResponseBody like you have it.  If we put it one level higher, then that would cause problems if the shipment uses more than one box as there would only be a single image for multiple boxes.

**Comment by CountZachula** [comment]
The aforementioned API change in fact placed the ImageUrl one level higher in the JSON response, hence my workaround suggestion. Unfortunately, the docs do not reflect the correct structure at the moment.

**Comment by jpshook** [comment]
Yeah, I noticed that in the response JSON.  Not sure why they made that
change in the API.

On Tue, Jan 7, 2014 at 10:28 AM, Zach Harbort notifications@github.comwrote:

> The aforementioned API change in fact placed the ImageUrl one level higher
> in the JSON response, hence my workaround suggestion. Unfortunately, the
> docs do not reflect the correct structure at the moment.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/postmaster/postmaster-csharp/issues/24#issuecomment-31746693
> .

## 

"In the beginner's mind there are many possibilites, in the experts mind
there are few"
- zen master shunryu suzuki

"When everything is coming your way, you're in the wrong lane."
- Steven Wright

**Comment by CountZachula** [comment]
@jpshook,

I've pushed the fix to master. The NuGet package will be updated later today.

Thanks!

**Comment by jpshook** [comment]
Thanks for the quick work!

On Tue, Jan 7, 2014 at 12:37 PM, Zach Harbort notifications@github.comwrote:

> @jpshook https://github.com/jpshook,
> 
> I've pushed the fix to master. The NuGet package will be updated later
> today.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/postmaster/postmaster-csharp/issues/24#issuecomment-31759391
> .

## 

"In the beginner's mind there are many possibilites, in the experts mind
there are few"
- zen master shunryu suzuki

"When everything is coming your way, you're in the wrong lane."
- Steven Wright
