### ISSUE TITLE
Reasons for empty responses

### ISSUE THREAD

**Issue by jpshook** [peterruggero/postmaster-csharp#25]
When I pass in a lot of boxes or items to ship OR when I create a lot of boxes and then try to do fit request for even as few as 6 packages, I often get a JSON response that has empty values.  This should really be treated as error.  Is this happening due to some box / item limitations they have in place or a timeout?  Do you know what the box / item limitations are for the API?

**Comment by drosenthal** [comment]
Can you post a gist of the code that's giving you an issue?

**Comment by jpshook** [comment]
Here you go: https://gist.github.com/jpshook/8319937

This is the JSON sent and returned:

JSON request: {"packages":[{"width":6.0,"height":2.0,"length":9.0,"weight":0.3},{"width":6.0,"height":3.0,"length":9.0,"weight":0.3},{"width":7.0,"height":5.0,"length":9.0,"weight":0.5},{"width":9.0,"height":3.0,"length":12.0,"weight":0.5},{"width":4.0,"height":4.0,"length":28.0,"weight":0.4},{"width":9.0,"height":4.0,"length":13.0,"weight":0.6},{"width":8.0,"height":5.0,"length":12.0,"weight":0.5},{"width":8.0,"height":8.0,"length":8.0,"weight":0.6},{"width":6.0,"height":6.0,"length":16.0,"weight":0.4},{"width":14.0,"height":3.0,"length":14.0,"weight":0.6},{"width":7.0,"height":7.0,"length":14.0,"weight":0.7},{"width":9.0,"height":6.0,"length":13.0,"weight":0.5},{"width":10.0,"height":4.0,"length":18.0,"weight":0.5},{"width":10.0,"height":6.0,"length":13.0,"weight":0.5},{"width":14.0,"height":4.0,"length":14.0,"weight":0.6},{"width":12.0,"height":4.0,"length":18.0,"weight":0.6},{"width":12.0,"height":4.0,"length":20.0,"weight":0.5},{"width":10.0,"height":8.0,"length":12.0,"weight":0.6},{"width":16.0,"height":4.0,"length":16.0,"weight":0.6},{"width":14.0,"height":4.0,"length":20.0,"weight":0.6},{"width":9.0,"height":9.0,"length":14.0,"weight":0.6},{"width":14.0,"height":7.0,"length":14.0,"weight":0.6},{"width":12.0,"height":6.0,"length":20.0,"weight":0.5},{"width":14.0,"height":6.0,"length":18.0,"weight":0.6},{"width":16.0,"height":6.0,"length":16.0,"weight":0.5},{"width":12.0,"height":6.0,"length":24.0,"weight":0.6},{"width":12.0,"height":8.0,"length":20.0,"weight":0.6},{"width":14.0,"height":8.0,"length":20.0,"weight":0.6},{"width":18.0,"height":8.0,"length":18.0,"weight":0.5},{"width":13.0,"height":10.0,"length":20.0,"weight":0.6},{"width":14.0,"height":8.0,"length":24.0,"weight":0.6},{"width":14.0,"height":14.0,"length":14.0,"weight":0.7},{"width":12.0,"height":12.0,"length":20.0,"weight":0.5},{"width":20.0,"height":6.0,"length":24.0,"weight":0.6},{"width":14.0,"height":12.0,"length":20.0,"weight":0.6},{"width":15.0,"height":12.0,"length":24.0,"weight":0.6},{"width":20.0,"height":14.0,"length":20.0,"weight":0.8}],"items":[{"width":11.7,"height":8.0,"length":19.7,"name":"2302-1","sku":"2302-1","count":1},{"width":11.7,"height":8.0,"length":19.7,"name":"2302-2","sku":"2302-2","count":1},{"width":11.7,"height":8.0,"length":19.7,"name":"2302-3","sku":"2302-3","count":1},{"width":11.7,"height":1.0,"length":19.7,"name":"2305-1","sku":"2305-1","count":1},{"width":11.7,"height":1.0,"length":19.7,"name":"2305-2","sku":"2305-2","count":1}]}

JSON response: {"leftovers": [], "boxes": [], "all_fit": false}

**Comment by CountZachula** [comment]
Thanks for your patience. I am currently looking into and trying to reproduce your issue.

**Comment by CountZachula** [comment]
@jpshook,

This is actually a limitation of the API. The server will send an empty response after so many failed iterations. Try to keep the number of item/box combinations below 10 per request.

Thanks!

**Comment by jpshook** [comment]
I figured it must be something like this.

Regards

JP

On Thu, Jan 9, 2014 at 12:44 PM, Zach Harbort notifications@github.comwrote:

> @jpshook https://github.com/jpshook,
> 
> This is actually a limitation of the API. Try to keep the number of
> item/box combinations below 10 per request.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/postmaster/postmaster-csharp/issues/25#issuecomment-31957677
> .

## 

"In the beginner's mind there are many possibilites, in the experts mind
there are few"
- zen master shunryu suzuki

"When everything is coming your way, you're in the wrong lane."
- Steven Wright
