### ISSUE TITLE
Porblem in getrate() method

### ISSUE THREAD

**Issue by rajnipadhiyar** [peterruggero/postmaster-csharp#27]
I want to pass heigth,weight,length for getting rate method so please update the project and include this 3 things and let me know 
waiting for your positive reply

**Comment by mentat** [comment]
@MorbidZach can you take a look at this one?

**Comment by rajnipadhiyar** [comment]
@MorbidZach  Thanks for the help one more issue is there i am  frequently getting this error:
"an item with the same key has already been added"

Can you pls help me?

**Comment by CountZachula** [comment]
@rajnipadhiyar No problem!

Could you explain with more detail the steps to reproduce the error? Also, can you provide the error's entire output so that I may be of better assistance?

Thanks,
Z
