### ISSUE TITLE
Sub account Carrier Setup

### ISSUE THREAD

**Issue by rajnipadhiyar** [peterruggero/postmaster-csharp#29]
Hi Team,

Partner api's "Create an Account" works perfectly. I have successfully created two accounts.
It returned account Id and Key, It works awesome. Thanks !

Now I am trying to setup fedex account into each of above accounts.
the method I am trying is Carrier Setup (POST /v1/settings/carriers)
Question is how to reference above account's in request parameters of carrier setup api?

In authorization?
I tried multiple ways but It always returned 404 error.

Thanks & Regards,
Rajni Padhiyar

**Comment by mentat** [comment]
Hi Rajni,

You'll need to use the API key even, not the Partner API, to set the settings on the account.  Please contact us via the in-app messaging for more details.

Best,

Jesse
