### ISSUE TITLE
Label Printing 

### ISSUE THREAD

**Issue by ishaaqmuhammad** [peterruggero/postmaster-csharp#33]
As we get the package label url in shipment response how can we send request to printer to print this label?

**Comment by CountZachula** [comment]
Hey @ishaaqmuhammad,

The physical act of printing is actually outside the scope of this library as it is more concerned with consuming Postmaster's API. However, I suggest you check out the `System.Drawing.Printing` namespace:
- https://msdn.microsoft.com/en-us/library/system.drawing.printing(v=vs.110).aspx
- http://stackoverflow.com/questions/5750659/print-images-c-net

I hope this helps.

Thanks for using postmaster-csharp!
Z
